/**
 * OWNER: Nidhish (Person B) — Phase 7
 * Payslip PDF generation with PDFKit + optional company logo (local uploads).
 */
import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import { env } from "../../common/config/env.js";

export type PayslipPdfInput = {
  companyName: string;
  logoPath?: string | null;
  employeeName: string;
  loginId: string;
  month: number;
  year: number;
  grossEarnings: number;
  totalDeductions: number;
  netPay: number;
  payableDays: number;
  lopDays: number;
  totalWorkingDays: number;
  lines: { name: string; type: "EARNING" | "DEDUCTION"; amount: number }[];
};

function money(n: number) {
  return `INR ${n.toFixed(2)}`;
}

/**
 * Writes a real PDF to uploads/payslips and returns the public URL path.
 */
export async function renderPayslipPdf(payslipId: string, data: PayslipPdfInput): Promise<string> {
  const dir = path.resolve(env.UPLOAD_DIR, "payslips");
  fs.mkdirSync(dir, { recursive: true });
  const filename = `payslip-${payslipId}.pdf`;
  const filePath = path.join(dir, filename);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    stream.on("finish", () => resolve());
    stream.on("error", reject);
    doc.on("error", reject);

    if (data.logoPath && fs.existsSync(data.logoPath)) {
      try {
        doc.image(data.logoPath, 50, 40, { fit: [72, 72] });
      } catch {
        /* ignore bad image */
      }
    }

    doc
      .fontSize(18)
      .text(data.companyName || "Dayflow HRMS", data.logoPath ? 130 : 50, 50, { align: "left" });
    doc.fontSize(11).fillColor("#555").text("Payslip", data.logoPath ? 130 : 50, 74);
    doc.fillColor("#000");

    doc.moveDown(3);
    doc.fontSize(12).text(`Employee: ${data.employeeName} (${data.loginId})`);
    doc.text(`Period: ${data.month}/${data.year}`);
    doc.text(
      `Working days: ${data.totalWorkingDays}  |  Payable: ${data.payableDays}  |  LOP: ${data.lopDays}`,
    );
    doc.moveDown();

    doc.fontSize(13).text("Earnings", { underline: true });
    doc.moveDown(0.5);
    for (const line of data.lines.filter((l) => l.type === "EARNING")) {
      doc.fontSize(11).text(`${line.name}`, { continued: true });
      doc.text(money(line.amount), { align: "right" });
    }
    doc.moveDown();
    doc.fontSize(13).text("Deductions", { underline: true });
    doc.moveDown(0.5);
    for (const line of data.lines.filter((l) => l.type === "DEDUCTION")) {
      doc.fontSize(11).text(`${line.name}`, { continued: true });
      doc.text(money(line.amount), { align: "right" });
    }

    doc.moveDown(1.5);
    doc.fontSize(12).text(`Gross earnings: ${money(data.grossEarnings)}`);
    doc.text(`Total deductions: ${money(data.totalDeductions)}`);
    doc.fontSize(14).text(`Net pay: ${money(data.netPay)}`, { underline: true });

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#888").text("Generated by Dayflow HRMS", { align: "center" });
    doc.end();
  });

  return `/uploads/payslips/${filename}`;
}
